service: powertools-lambda-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 's3:*'
        - Effect: 'Allow'
          Resource: '*'
          Action: 'sqs:*'
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:us-east-1:934396891861:table/tickets

functions:
  user-handler:
    handler: src.hero_handler.handler
    events:
      - httpApi:
          path: /tickets
          method: get
      - httpApi:
          path: /tickets/{id}
          method: get

plugins:
  - serverless-offline
  - serverless-python-requirements
